### ISSUE TITLE
Work out where guides should live

### ISSUE THREAD

**Issue by rmccue** [humanmade/platform-documentation#8]
Right now, I'm working on guides in a separate repo at https://github.com/humanmade/platform-guides/

We have three ways we could handle this, and we should decide which we'd prefer:

* **Separate repo**: Keep the docs in a separate repo, and pull them down as part of the docs module. As they're meta-docs (not related to any module), this most closely matches the type of docs as it keeps them separate but still manageable via PRs.
* **Include in `core` module**: We could include guides as the `core` module's documentation, as this is a hidden/internal module, and the closest to being a "meta" module (apart from the literal meta module).
* **Store as WP post/page content**: We could store the guides in regular WP posts/pages, and have the documentation module render the content of those.

Storing the guides in a repo or in WP content would allow us to manage them separately to releases (if we want to; we don't *have* to), which could have benefits if best practices change outside of a release cycle. We could in theory do these in minor updates instead, but that's a bit of an abuse of the release process.

Storing in the `core` module would mean that we likely wouldn't be able to introduce documentation for the core module later without some hacks. We'd likely need to special-case it anyway.

@joehoyle @roborourke thoughts?

**Comment by joehoyle** [comment]
I'm +1 on putting them in `core`. I think in _most_ cases the "Getting started" content will want to be version specific, as we are likely to be changing those meta level things between release.

Perhaps "Getting Started" isn't exactly the same things as "Building Decoupled with Altis" guide, though even with that example, we'd at least need to also caveat which versions of Altis the guide was written for.

So, +1 for our getting started docs in core, still a but unsure on blog style guides

**Comment by roborourke** [comment]
Agree with @joehoyle here. Guides like getting started, how to config, updating modules to RC etc are either evergreen or related to the current version so should live in the core module.

It gets a little fuzzy where elements that could be on separate versions are involved (thinking CLI, maybe local server if we don't bundle / suggest the package) but I'm not sure that's avoidable. As long as that's considered and there's version check in there we should be ok.

**Comment by roborourke** [comment]
Blog type guides are going to be those that aren't core to the development experience, not required knowledge to use platform and less likely to be evergreen.

My gut feel is that these can live on the altis site, as a blog category or separate content type. Alternatively they could live on zendesk as part of the knowledgebase, either way there needs to be an archive, tagging and an API to fetch them.

**Comment by rmccue** [comment]
We've moved these into this module for now. Let's see how it works out for now, and possibly move later.
